/* Room content: chemistry */

export default {
name: "Chemistry", kind: "Matter", glyph: "🧪", color: "#e0794b",
blurb: "Where the periodic table becomes reactions — bonding, equations, solutions, acids/bases, equilibrium, thermodynamics, kinetics, and organic foundations.",
status: "Live — five solvers, plus formulas and worked examples",
topics: [
  "Atoms & ions", "Elements & compounds", "Periodic trends", "Electron configuration", "Bonding",
  "Ionic bonds", "Covalent bonds", "Molecular geometry", "Intermolecular forces", "Chemical equations",
  "Stoichiometry", "Moles & molar mass", "Solutions & concentration", "Acids & bases", "Buffers",
  "Equilibrium", "Thermodynamics", "Kinetics", "Redox", "Electrochemistry", "Organic basics", "Lab calculations"
],
cards: [
  { name: "Mole relationship", body: "n = m / M", note: "moles = mass ÷ molar mass." },
  { name: "Avogadro's number", body: "N<sub>A</sub> = 6.022 × 10²³ /mol", note: "particles per mole." },
  { name: "Molarity", body: "M = mol / L", note: "moles of solute per litre of solution (mol/L)." },
  { name: "Dilution", body: "M₁V₁ = M₂V₂", note: "concentration × volume is conserved on dilution." },
  { name: "Percent composition", body: "%X = (mass of X / molar mass) × 100", note: "" },
  { name: "Empirical formula", body: "smallest whole-number mole ratio of the elements", note: "% → moles → divide by the smallest." },
  { name: "Ideal gas law", body: "PV = nRT", note: "R = 0.0821 L·atm/mol·K  (8.314 J/mol·K). Temperature must be in kelvin, and R must match your pressure unit." },
  { name: "Combined gas law", body: "P₁V₁/T₁ = P₂V₂/T₂", note: "Boyle, Charles and Gay-Lussac are all this equation with one quantity held constant." },
  { name: "Molar volume at STP", body: "1 mol of any ideal gas = <b>22.4 L</b> at 0 °C and 1 atm.", note: "IUPAC's STP is 0 °C and 100 kPa, giving 22.7 L — check which one your course uses." },
  { name: "Dalton's law", body: "P<sub>total</sub> = ΣP<sub>i</sub> · P<sub>i</sub> = X<sub>i</sub>·P<sub>total</sub>", note: "X<sub>i</sub> = n<sub>i</sub>/n<sub>total</sub>; mole fractions add to 1." },
  { name: "Graham's law", body: "rate₁ / rate₂ = √(M₂ / M₁)", note: "Lighter gases effuse faster. Times are the inverse of rates." },
  { name: "Gas density", body: "d = PM / RT, so M = dRT / P", note: "Lets you find molar mass from a measured gas density." },
  { name: "pH and pOH", body: "pH = −log[H⁺] · pH + pOH = 14", note: "" },
  { name: "Ka and Kb", body: "K<sub>a</sub> · K<sub>b</sub> = K<sub>w</sub> = 1 × 10⁻¹⁴", note: "stronger acid ⇒ larger K<sub>a</sub>." },
  { name: "Henderson–Hasselbalch", body: "pH = pK<sub>a</sub> + log([A⁻] / [HA])", note: "buffer pH from the conjugate ratio." },
  { name: "Equivalence point", body: "Where moles of titrant = moles of analyte.", note: "Equivalence means <b>stoichiometrically equal</b>, not pH 7 — only strong + strong lands on 7." },
  { name: "Half-equivalence", body: "At half the equivalence volume, [HA] = [A⁻], so <b>pH = pK<sub>a</sub></b>.", note: "This is how a pKₐ is read off a titration curve, and it is the point of best buffering." },
  { name: "Equivalence pH by type", body: "Strong + strong → 7<br>Weak acid + strong base → &gt; 7<br>Weak base + strong acid → &lt; 7", note: "The leftover conjugate decides which side of neutral you land on." },
  { name: "Choosing an indicator", body: "Pick one whose colour-change range contains the equivalence pH.", note: "Phenolphthalein (8.3–10.0) for weak acid + strong base; methyl red (4.4–6.2) for weak base + strong acid." },
  { name: "Titration calculation", body: "M<sub>a</sub>V<sub>a</sub> = M<sub>b</sub>V<sub>b</sub> (for a 1:1 reaction)", note: "For other ratios, carry the mole ratio from the balanced equation." },
  { name: "Equilibrium constant", body: "K = [products] / [reactants]", note: "each term raised to its coefficient. Q vs K predicts the shift (Le Chatelier)." },
  { name: "Heat and temperature change", body: "q = m·c·ΔT, where ΔT = T<sub>final</sub> − T<sub>initial</sub>", note: "c for water = 4.184 J/(g·°C). Positive q = absorbed, negative q = released." },
  { name: "Endothermic vs exothermic", body: "Exothermic: releases heat, ΔH &lt; 0, surroundings warm up.<br>Endothermic: absorbs heat, ΔH &gt; 0, surroundings cool down.", note: "The sign is from the system's point of view, not yours." },
  { name: "Enthalpy from formation values", body: "ΔH°<sub>rxn</sub> = Σ n·ΔH°<sub>f</sub>(products) − Σ n·ΔH°<sub>f</sub>(reactants)", note: "An element in its standard state has ΔH°<sub>f</sub> = 0, so those terms drop out." },
  { name: "Hess's law", body: "Enthalpy is a state function — ΔH depends only on start and end, not the route.", note: "Reverse a step ⇒ flip the sign. Double a step ⇒ double its ΔH." },
  { name: "Phase changes", body: "q = n·ΔH<sub>fus</sub> or n·ΔH<sub>vap</sub>. Water: 6.02 kJ/mol to melt, 40.7 kJ/mol to boil.", note: "Temperature holds constant during a phase change, so q = mcΔT does not apply there." },
  { name: "Gibbs free energy", body: "ΔG = ΔH − TΔS · ΔG = −RT ln K", note: "ΔG &lt; 0 ⇒ spontaneous." },
  { name: "Reaction rate", body: "rate = k[A]<sup>m</sup>[B]<sup>n</sup>", note: "orders m, n are found experimentally." },
  { name: "Redox (OIL RIG)", body: "Oxidation Is Loss, Reduction Is Gain of e⁻", note: "oxidizing agent is reduced; reducing agent is oxidized." },
  { name: "Nernst equation", body: "E = E° − (RT / nF) ln Q", note: "cell potential away from standard conditions." },
  { name: "Electronegativity trend", body: "↑ across a period · ↓ down a group", note: "peaks at fluorine." },
  { name: "Ionization energy trend", body: "↑ across a period · ↓ down a group", note: "" },
  { name: "Atomic radius trend", body: "↓ across a period · ↑ down a group", note: "" }
],
examples: [
  { q: "Molar mass of H₂O", steps: ["H: 2 × 1.008 = 2.016", "O: 1 × 16.00 = 16.00", "Add them"], ans: "<b>18.02 g/mol</b>" },
  { q: "Convert 36 g of H₂O to moles", steps: ["n = m / M = 36 / 18.02"], ans: "≈ <b>2.0 mol</b>" },
  { q: "Molarity of 0.5 mol NaCl in 2 L", steps: ["M = mol / L = 0.5 / 2"], ans: "<b>0.25 M</b>" },
  { q: "Dilute 2 M stock to 0.5 M in 100 mL", steps: ["M₁V₁ = M₂V₂", "V₁ = (0.5 × 100) / 2"], ans: "<b>25 mL</b> of stock, then top up to 100 mL" },
  { q: "Balance  H₂ + O₂ → H₂O", steps: ["Balance O with 2 H₂O", "Balance H with 2 H₂"], ans: "<b>2 H₂ + O₂ → 2 H₂O</b>" },
  { q: "From 4 mol H₂ in  2 H₂ + O₂ → 2 H₂O", steps: ["H₂ : H₂O ratio = 2 : 2 = 1 : 1"], ans: "<b>4 mol H₂O</b> (consumes 2 mol O₂)" },
  { q: "pH when [H⁺] = 1 × 10⁻³ M", steps: ["pH = −log(10⁻³)"], ans: "pH = <b>3</b>" },
  { q: "Buffer pH: pK<sub>a</sub> = 4.74, [A⁻] = [HA]", steps: ["pH = pK<sub>a</sub> + log(1)", "log 1 = 0"], ans: "pH = <b>4.74</b>" },
  { q: "Redox: Zn + Cu²⁺ → Zn²⁺ + Cu", steps: ["Zn → Zn²⁺ + 2e⁻ (loses electrons)", "Cu²⁺ + 2e⁻ → Cu (gains electrons)"], ans: "Zn is <b>oxidized</b>, Cu²⁺ is <b>reduced</b>" },
  { q: "Titrating 25.0 mL of 0.100 M HCl with 0.100 M NaOH — equivalence volume?", steps: ["moles HCl = 0.100 × 0.0250 = 2.50 mmol", "1:1 reaction, so 2.50 mmol NaOH needed", "V = 2.50 mmol ÷ 0.100 M"], ans: "<b>25.0 mL</b>, and the pH there is <b>7.00</b>" },
  { q: "Why is the equivalence point of acetic acid + NaOH above pH 7?", steps: ["At equivalence, all the acetic acid has become acetate", "Acetate is a weak base — it takes H⁺ from water", "That leaves excess OH⁻"], ans: "pH ≈ <b>8.7</b>, basic — not 7" },
  { q: "Read a pKₐ off a titration curve", steps: ["Find the equivalence volume", "Halve it", "Read the pH at that volume"], ans: "that pH <b>is the pKₐ</b>" },
  { q: "Which indicator for a weak base titrated with strong acid?", steps: ["Equivalence pH is below 7 (≈ 5.3 for ammonia)", "Need an indicator changing near there"], ans: "<b>methyl red</b> (4.4–6.2), not phenolphthalein" },
  { q: "Volume of 1.00 mol of gas at 0 °C and 1.00 atm", steps: ["V = nRT/P", "T must be kelvin: 0 °C = 273 K", "V = (1.00 × 0.0821 × 273) / 1.00"], ans: "<b>22.4 L</b> — the molar volume at STP" },
  { q: "A gas at 1.00 atm and 2.00 L is compressed to 2.00 atm at fixed T", steps: ["T constant ⇒ Boyle's law: P₁V₁ = P₂V₂", "V₂ = (1.00 × 2.00) / 2.00"], ans: "<b>1.00 L</b> — double the pressure, half the volume" },
  { q: "2.00 L at 27 °C is heated to 327 °C at fixed P", steps: ["P constant ⇒ Charles's law: V₁/T₁ = V₂/T₂", "Convert: 300 K and 600 K", "V₂ = 2.00 × 600/300"], ans: "<b>4.00 L</b> — doubling absolute T doubles V" },
  { q: "Partial pressure of O₂ in dry air at 1.00 atm", steps: ["Air is ~21% O₂ by moles, so X = 0.21", "P = X · P_total = 0.21 × 1.00"], ans: "<b>0.21 atm</b>" },
  { q: "How much faster does He effuse than O₂?", steps: ["M(He) = 4.00, M(O₂) = 32.0", "rate ratio = √(32.0 / 4.00) = √8.00"], ans: "<b>2.83×</b> faster" },
  { q: "Heat to warm 100 g of water from 25 °C to 75 °C", steps: ["ΔT = 75 − 25 = 50 °C", "q = m·c·ΔT = 100 × 4.184 × 50"], ans: "<b>20 920 J = 20.9 kJ</b> absorbed" },
  { q: "Final temperature after adding 5 000 J to 200 g of water at 20 °C", steps: ["ΔT = q / (m·c) = 5000 / (200 × 4.184) = 5.98 °C", "T = 20 + 5.98"], ans: "<b>26.0 °C</b>" },
  { q: "ΔH°rxn for CH₄(g) + 2 O₂(g) → CO₂(g) + 2 H₂O(l)", steps: ["Products: −393.5 + 2(−285.8) = −965.1 kJ", "Reactants: −74.6 + 2(0) = −74.6 kJ", "Subtract: −965.1 − (−74.6)"], ans: "<b>−890.5 kJ</b> — exothermic" },
  { q: "Why is O₂(g) worth zero in that sum?", steps: ["ΔH°f is the enthalpy to form 1 mol from its elements", "O₂(g) already <i>is</i> the element in its standard state", "Forming it from itself costs nothing"], ans: "ΔH°<sub>f</sub> of any element in its standard state = <b>0</b>" },
  { q: "Hess: find ΔH for C(s) + ½O₂(g) → CO(g)", steps: ["C(s) + O₂ → CO₂, ΔH = −393.5 kJ", "CO + ½O₂ → CO₂, ΔH = −283.0 kJ — reverse it: +283.0", "Add: −393.5 + 283.0"], ans: "<b>−110.5 kJ</b>" },
  { q: "Why does NaCl form? (connect to the table)", steps: ["Na (Z 11) loses 1e⁻ → Na⁺", "Cl (Z 17) gains 1e⁻ → Cl⁻", "Opposite charges attract"], ans: "<b>Na⁺Cl⁻</b> — open the Periodic Table room to inspect Na &amp; Cl" }
],
links: [
  { name: "Open Periodic Table", desc: "The elements behind every reaction.", href: "room.html?room=periodic-table", tag: "room" },
  { name: "Data, Symbols & Units", desc: "Chemical notation, units, constants & calculator.", href: "room.html?room=data-analysis", tag: "room" },
  { name: "Open Biochemistry", desc: "Where chemistry meets biology — enzymes, metabolism.", href: "room.html?room=biochemistry", tag: "room" },
  { name: "Open Lab Methods", desc: "Solution prep, titrations, chromatography, calibration.", href: "room.html?room=lab-methods", tag: "room" },
  { name: "Open Physics & Math", desc: "Energy, gas laws, and measurement.", href: "room.html?room=physics", tag: "room" },
  { name: "Math Lab", desc: "Algebra, calculus, statistics — the full toolset.", href: "../math/", tag: "math" },
]
};
